# Generated by Django 4.2.2 on 2023-06-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huzas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ev', models.IntegerField()),
                ('het', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Húzás',
                'verbose_name_plural': 'Húzások',
            },
        ),
        migrations.CreateModel(
            name='Nyeremeny',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('talalat', models.IntegerField()),
                ('darab', models.IntegerField()),
                ('ertek', models.IntegerField()),
                ('huzasid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lotto.huzas')),
            ],
            options={
                'verbose_name': 'Nyeremény',
                'verbose_name_plural': 'Nyeremények',
            },
        ),
        migrations.CreateModel(
            name='Huzott',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('szam', models.IntegerField()),
                ('huzasid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lotto.huzas')),
            ],
            options={
                'verbose_name': 'Húzott',
                'verbose_name_plural': 'Húzottak',
            },
        ),
    ]
